"""empty message

Revision ID: 6f9566bc355c
Revises: c4d09121ca35
Create Date: 2018-01-30 15:15:21.746833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9566bc355c'
down_revision = 'c4d09121ca35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplina', sa.Column('visivel', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disciplina', 'visivel')
    # ### end Alembic commands ###
