"""empty message

Revision ID: 9883e973f262
Revises: abdb1e0b66d7
Create Date: 2018-02-16 16:50:19.246652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9883e973f262'
down_revision = 'abdb1e0b66d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('visivel', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labs', 'visivel')
    # ### end Alembic commands ###
