"""empty message

Revision ID: b5335a3aef8f
Revises: 6faa15b4284a
Create Date: 2018-01-30 11:14:25.086349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5335a3aef8f'
down_revision = '6faa15b4284a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplina', sa.Column('chave', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disciplina', 'chave')
    # ### end Alembic commands ###
