"""empty message

Revision ID: c4d09121ca35
Revises: 7b092dd9a80b
Create Date: 2018-01-30 14:48:39.889818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d09121ca35'
down_revision = '7b092dd9a80b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_disc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_user', sa.Integer(), nullable=True),
    sa.Column('cod_dis', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cod_dis'], ['disciplina.id'], ),
    sa.ForeignKeyConstraint(['cod_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_disc')
    # ### end Alembic commands ###
