"""empty message

Revision ID: 11e592f524a3
Revises: 1ac290741480
Create Date: 2018-06-29 16:06:00.800533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e592f524a3'
down_revision = '1ac290741480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envios', sa.Column('codigo_subs', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('envios', 'codigo_subs')
    # ### end Alembic commands ###
