"""empty message

Revision ID: 1ac290741480
Revises: 4a0e90131b74
Create Date: 2018-05-14 15:17:47.930708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ac290741480'
down_revision = '4a0e90131b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disciplina', 'nomearquivo')
    op.add_column('labs', sa.Column('nomearquivo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labs', 'nomearquivo')
    op.add_column('disciplina', sa.Column('nomearquivo', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
