"""empty message

Revision ID: 2b8702770dc1
Revises: 0bb08e490ec3
Create Date: 2018-03-07 17:23:41.611052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b8702770dc1'
down_revision = '0bb08e490ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('envios', 'nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envios', sa.Column('nome', mysql.VARCHAR(length=10000), nullable=True))
    # ### end Alembic commands ###
