"""empty message

Revision ID: 3c8ef2524052
Revises: b93c96f50ae9
Create Date: 2017-12-19 16:01:16.797884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c8ef2524052'
down_revision = 'b93c96f50ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('convites', 'email_convidado',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('convites', 'mensagem_para_convidado',
               existing_type=mysql.VARCHAR(length=10000),
               nullable=False)
    op.alter_column('convites', 'nome_convidado',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('disciplina', 'nome_disc',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('envios', 'mensagem',
               existing_type=mysql.VARCHAR(length=10000),
               nullable=False)
    op.alter_column('envios', 'status',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('labs', 'descricao',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('labs', 'descricao',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('envios', 'status',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('envios', 'mensagem',
               existing_type=mysql.VARCHAR(length=10000),
               nullable=True)
    op.alter_column('disciplina', 'nome_disc',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('convites', 'nome_convidado',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('convites', 'mensagem_para_convidado',
               existing_type=mysql.VARCHAR(length=10000),
               nullable=True)
    op.alter_column('convites', 'email_convidado',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
