"""empty message

Revision ID: 4a0e90131b74
Revises: 7945580fd8b7
Create Date: 2018-05-14 15:16:40.277497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0e90131b74'
down_revision = '7945580fd8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplina', sa.Column('nomearquivo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disciplina', 'nomearquivo')
    # ### end Alembic commands ###
