"""empty message

Revision ID: 5aaaab0b47dd
Revises: 8c1317f1a313
Create Date: 2018-06-29 16:10:04.674617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5aaaab0b47dd'
down_revision = '8c1317f1a313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labs', 'nomearquivo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('nomearquivo', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
