"""empty message

Revision ID: 6785f66cb430
Revises: e7fb37149fb7
Create Date: 2018-03-08 17:38:48.448917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6785f66cb430'
down_revision = 'e7fb37149fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envios', sa.Column('linguagem', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('envios', 'linguagem')
    # ### end Alembic commands ###
