"""empty message

Revision ID: 6faa15b4284a
Revises: 3c8ef2524052
Create Date: 2017-12-19 17:03:00.305153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6faa15b4284a'
down_revision = '3c8ef2524052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disciplina', 'codigo_disc',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('labs', 'titulo',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labs', 'titulo',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('disciplina', 'codigo_disc',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
