"""empty message

Revision ID: 7945580fd8b7
Revises: 6785f66cb430
Create Date: 2018-03-09 15:02:16.593640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7945580fd8b7'
down_revision = '6785f66cb430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('titulo', table_name='labs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('titulo', 'labs', ['titulo'], unique=True)
    # ### end Alembic commands ###
