"""empty message

Revision ID: 7b092dd9a80b
Revises: b5335a3aef8f
Create Date: 2018-01-30 13:14:29.378638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b092dd9a80b'
down_revision = 'b5335a3aef8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labs', 'descricao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('descricao', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
