"""empty message

Revision ID: 8c1317f1a313
Revises: 11e592f524a3
Create Date: 2018-06-29 16:07:55.562925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c1317f1a313'
down_revision = '11e592f524a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('envios', 'codigo_subs')
    op.drop_column('envios', 'codigo_saida')
    op.add_column('labs', sa.Column('codigo_saida', sa.String(length=1000), nullable=True))
    op.add_column('labs', sa.Column('codigo_subs', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labs', 'codigo_subs')
    op.drop_column('labs', 'codigo_saida')
    op.add_column('envios', sa.Column('codigo_saida', mysql.VARCHAR(length=10000), nullable=True))
    op.add_column('envios', sa.Column('codigo_subs', mysql.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###
