"""empty message

Revision ID: abdb1e0b66d7
Revises: f25b6327d665
Create Date: 2018-02-06 15:06:38.012310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abdb1e0b66d7'
down_revision = 'f25b6327d665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('excluir', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labs', 'excluir')
    # ### end Alembic commands ###
