"""empty message

Revision ID: b93c96f50ae9
Revises: 
Create Date: 2017-12-18 17:44:33.604177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93c96f50ae9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_disc', sa.String(length=50), nullable=True),
    sa.Column('logo', sa.String(length=150), nullable=True),
    sa.Column('nome_disc', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_disc')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('professor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('convites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_convidado', sa.String(length=100), nullable=True),
    sa.Column('email_convidado', sa.String(length=100), nullable=True),
    sa.Column('mensagem_para_convidado', sa.String(length=10000), nullable=True),
    sa.Column('cod_remetente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cod_remetente'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=50), nullable=True),
    sa.Column('arquivo', sa.String(length=10000), nullable=True),
    sa.Column('disciplina_id', sa.Integer(), nullable=True),
    sa.Column('datahora', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.create_table('envios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('mensagem', sa.String(length=10000), nullable=True),
    sa.Column('cod_user', sa.Integer(), nullable=True),
    sa.Column('cod_lab', sa.Integer(), nullable=True),
    sa.Column('datahora', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cod_lab'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['cod_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('envios')
    op.drop_table('labs')
    op.drop_table('convites')
    op.drop_table('users')
    op.drop_table('disciplina')
    # ### end Alembic commands ###
