"""empty message

Revision ID: c33394922aa4
Revises: ec784f9a50ea
Create Date: 2018-03-06 17:38:18.972631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c33394922aa4'
down_revision = 'ec784f9a50ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envios', sa.Column('nomedasub', sa.String(length=10000), nullable=True))
    op.drop_column('envios', 'nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envios', sa.Column('nome', mysql.VARCHAR(length=10000), nullable=True))
    op.drop_column('envios', 'nomedasub')
    # ### end Alembic commands ###
