"""empty message

Revision ID: e7fb37149fb7
Revises: 2b8702770dc1
Create Date: 2018-03-07 17:24:24.985348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7fb37149fb7'
down_revision = '2b8702770dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envios', sa.Column('nome', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('envios', 'nome')
    # ### end Alembic commands ###
