"""empty message

Revision ID: ec784f9a50ea
Revises: 9883e973f262
Create Date: 2018-03-06 17:35:23.639847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec784f9a50ea'
down_revision = '9883e973f262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envios', sa.Column('nome', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('envios', 'nome')
    # ### end Alembic commands ###
