"""empty message

Revision ID: f25b6327d665
Revises: d5f5481feeee
Create Date: 2018-02-06 15:05:07.064885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25b6327d665'
down_revision = 'd5f5481feeee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplina', sa.Column('excluir', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disciplina', 'excluir')
    # ### end Alembic commands ###
